relativeURLs = true
title = "Gautam Rao"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Associate Professor of Business and Economics, University of California, Berkeley"
    logo = "Rao_headshot_berkeley.jpg" 
    
