relativeURLs = true
title = "Maithreyi Gopalan"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
#ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Associate Professor, University of Oregon"
    logo = "headshot_Gopalan.jpg" 
    
